#lang racket

(define (principal4)
  (begin
    (display "Holi!")
    )
  )

(define (descuento? carnes frutas verduras descuento)
  (define valor-carne (* carnes 0.94))
  (define valor-fruta (* frutas 0.95))
  (define valor-verdura (* verduras 0.93))
  (cond
    ((and (> valor-carne valor-fruta) (> valor-carne valor-verdura))
     (if (> valor-fruta valor-verdura)
         (begin (* descuento (+ (* valor-carne 0.95) (* valor-verdura 0.97) valor-verdura)))
         (begin (* descuento (+ (* valor-carne 0.95) (* valor-verdura 0.97) valor-fruta)))
         )
     )
    ((and (> valor-fruta valor-carne) (> valor-fruta valor-verdura))
     (if (> valor-carne valor-verdura)
         (begin (* descuento (+ (* valor-fruta 0.95) (* valor-carne 0.97) valor-verdura)))
         (begin (* descuento (+ (* valor-fruta 0.95) (* valor-verdura 0.97) valor-carne)))
         )
     )
    ((and (> valor-verdura valor-carne) (> valor-verdura valor-fruta))
     (if (> valor-carne valor-fruta)
         (begin (* descuento (+ (* valor-verdura 0.95) (* valor-carne 0.97) valor-fruta)))
         (begin (* descuento (+ (* valor-verdura 0.95) (* valor-fruta 0.97) valor-carne)))
         )
     )
    )
  )

(define (costo? dia carne frutas verduras)
  (if (odd? dia)
      (begin (descuento? carne frutas verduras 1))
      (begin (descuento? carne frutas verduras 0.93))
      )
  )

(define (principal3)
  (begin
    (display "Ingrese el día del mes: ")
    (define dia (read))
    (display "Ingrese el valor de la carne: ")
    (define valor-carne (read))
    (display "Ingrese el valor de las frutas: ")
    (define valor-frutas (read))
    (display "Ingrese el valor de las verduras: ")
    (define valor-verduras (read))
    (costo? dia valor-carne valor-frutas valor-verduras)
    )
  )

(define (cobro? edad hora)
  (cond
    ((< edad 4) "¡Entra gratis!")
    ((and (and (>= edad 4) (< edad 18)))
     (cond
       ((and (>= hora 8) (< hora 10)) (/ 50 2))
       ((and (>= hora 12) (< hora 14)) (* 50 0.72))
       ((and (>= hora 2) (< hora 16)) (* 50 2))
       (else 50)
       )
     )
    ((>= edad 18)
     (cond
       ((and (>= hora 8) (< hora 10)) (* 100 0.44))
       (else 100)
       )
     )
    )
  )

(define (principal2)
  (begin
    (display "Ingrese la edad del cliente: ")
    (define edad (read))
    (display "Ingrese la hora de ingreso del cliente [0-24]: ")
    (define hora (read))
    (display "Debe cobrar $")(displayln (cobro? edad hora))
    )
  )

(define (fib n)
  (if (or (= n 0) (= n 1))
      (begin n)
      (begin
        (+ (fib (- n 1)) (fib (- n 2)))
        )
      )
  )

(define (principal1)
  (begin
    (display "Ingrese la posición deseada para el número de la sucesión de Fibonacci [n]\n~: ")
    (define number (read))
    (display "Fib(n) = ")(displayln (fib number))
    (display "f(n) = ")(displayln (+ (fib number) (expt (fib number) (fib number))))
    )
  )

(define (decorator option-len option-char)
  (define (line len char) (make-string len char))
  (cond
    ((= option-char 1) (line option-len #\-)) ;inicio y fin del programa
    ((= option-char 2) (line option-len #\*))
    ((= option-char 3) (line option-len #\#))
    (else "¡¡Decorador no definido!!")
    )
  )

(define (bye)
  (displayln "¡Adiós!")
  (displayln (decorator 50 1))
  )

(define (menu.option?)
  (display "~: ")
  (define option (read))
  (cond
    ((= option 0) (bye))
    ((= option 1) (principal1))
    ((= option 2) (principal2))
    ((= option 3) (principal3))
    ((= option 4) "4")
    ((= option 5) "5")
    ((= option 6) "6")
    ((= option 7) "7")
    ((= option 8) "8")
    ((= option 9) "9")
    ((= option 10) "10")
    (else (begin
            (displayln "Opción no definida, intente de nuevo")
            (menu.option?)
            ))
    )
  )

(define (menu)
  (begin
    (define len-decorator 50)
    (displayln (decorator len-decorator 1))
    (displayln "¡Bienvenido!")(newline)
    (displayln "Por favor, elija una de las siguientes opciones: ")
    (displayln "Salir [0]")
    (displayln "Ejercicio 4 [1]")
    (displayln "Ejercicio 5 [2]")
    (displayln "Ejercicio 6 [3]")
    (displayln "Ejercicio 7 [4]")
    (displayln "Ejercicio 8 [5]")
    (displayln "Ejercicio 9 [6]")
    (displayln "Ejercicio 10 [7]")
    (displayln "Ejercicio 11 [8]")
    (displayln "Ejercicio 12 [9]")
    (displayln "Ejercicio 13 [10]")
    (displayln (decorator len-decorator 2))
    (menu.option?)
    )
  )

(menu)